/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,jsx,js}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
      },
      colors: {
        light: {
          primary: '#A033FF',
          surfaceTint: '#A033FF',
          onPrimary: '#FFFFFF',
          primaryContainer: '#F2D6FF',
          onPrimaryContainer: '#2B0057',
          secondary: '#6B4D80',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#F0DAFF',
          onSecondaryContainer: '#24154A',
          tertiary: '#6A4AA0',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#E6DEFF',
          onTertiaryContainer: '#1D0065',
          error: '#BA1A1A',
          onError: '#FFFFFF',
          errorContainer: '#FFDAD6',
          onErrorContainer: '#410002',
          background: '#FCF7FF',
          onBackground: '#1D1B22',
          surface: '#FCF7FF',
          onSurface: '#1D1B22',
          surfaceVariant: '#EBE0F0',
          onSurfaceVariant: '#4B4554',
          outline: '#7C7586',
          outlineVariant: '#CECAD6',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#322F38',
          inverseOnSurface: '#F3EDFA',
          inversePrimary: '#D9B8FF',
          primaryFixed: '#F2D6FF',
          onPrimaryFixed: '#2B0057',
          primaryFixedDim: '#D9B8FF',
          onPrimaryFixedVariant: '#7F00DE',
          secondaryFixed: '#F0DAFF',
          onSecondaryFixed: '#24154A',
          secondaryFixedDim: '#D4BEE9',
          onSecondaryFixedVariant: '#51376B',
          tertiaryFixed: '#E6DEFF',
          onTertiaryFixed: '#1D0065',
          tertiaryFixedDim: '#C7BDFF',
          onTertiaryFixedVariant: '#4F3388',
          surfaceDim: '#DDD8E3',
          surfaceBright: '#FCF7FF',
          surfaceContainerLowest: '#FFFFFF',
          surfaceContainerLow: '#F5F0FC',
          surfaceContainer: '#EFEAF6',
          surfaceContainerHigh: '#E9E4F0',
          surfaceContainerHighest: '#E3DEEA',
        },
        dark: {
          primary: '#D9B8FF',
          surfaceTint: '#D9B8FF',
          onPrimary: '#4A008A',
          primaryContainer: '#7F00DE',
          onPrimaryContainer: '#F2D6FF',
          secondary: '#D4BEE9',
          onSecondary: '#392960',
          secondaryContainer: '#51376B',
          onSecondaryContainer: '#F0DAFF',
          tertiary: '#C7BDFF',
          onTertiary: '#301F79',
          tertiaryContainer: '#4F3388',
          onTertiaryContainer: '#E6DEFF',
          error: '#FFB4AB',
          onError: '#690005',
          errorContainer: '#93000A',
          onErrorContainer: '#FFDAD6',
          background: '#13101A',
          onBackground: '#E5DFEC',
          surface: '#13101A',
          onSurface: '#E5DFEC',
          surfaceVariant: '#4B4554',
          onSurfaceVariant: '#CEC9D6',
          outline: '#97919F',
          outlineVariant: '#4B4554',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#E5DFEC',
          inverseOnSurface: '#322F38',
          inversePrimary: '#A033FF',
          primaryFixed: '#F2D6FF',
          onPrimaryFixed: '#2B0057',
          primaryFixedDim: '#D9B8FF',
          onPrimaryFixedVariant: '#7F00DE',
          secondaryFixed: '#F0DAFF',
          onSecondaryFixed: '#24154A',
          secondaryFixedDim: '#D4BEE9',
          onSecondaryFixedVariant: '#51376B',
          tertiaryFixed: '#E6DEFF',
          onTertiaryFixed: '#1D0065',
          tertiaryFixedDim: '#C7BDFF',
          onTertiaryFixedVariant: '#4F3388',
          surfaceDim: '#13101A',
          surfaceBright: '#3B3843',
          surfaceContainerLowest: '#0F0C15',
          surfaceContainerLow: '#1D1B22',
          surfaceContainer: '#211F26',
          surfaceContainerHigh: '#2B2930',
          surfaceContainerHighest: '#36343C',
        },
      },
      space: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
        13: '52px',
        14: '56px',
        15: '60px',
        16: '64px',
        17: '68px',
        18: '72px',
        19: '76px',
        20: '80px',
        21: '84px',
        22: '88px',
        23: '92px',
        24: '96px',
        25: '100px',
        26: '104px',
        27: '108px',
        28: '112px',
        29: '116px',
        30: '120px',
      },
      boxShadow: {
        elevation1:
          '0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
        elevation2:
          '0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
        elevation3:
          '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)',
        elevation4:
          '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)',
        elevation5:
          '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)',
      },
      borderRadius: {
        none: '0',
        extraSmall: '4px',
        small: '8px',
        medium: '12px',
        large: '16px',
        extraLarge: '28px',
        full: '1000px',
      },
      fontSize: {
        displayLarge: [
          '57px',
          {
            fontWeight: '400',
            lineHeight: '64px',
            letterSpacing: '-0.25px',
          },
        ],
        displayMedium: [
          '45px',
          {
            fontWeight: '400',
            lineHeight: '52px',
            letterSpacing: '0',
          },
        ],
        displaySmall: [
          '36px',
          {
            fontWeight: '400',
            lineHeight: '44px',
            letterSpacing: '0',
          },
        ],
        headlineLarge: [
          '32px',
          {
            fontWeight: '400',
            lineHeight: '40px',
            letterSpacing: '0',
          },
        ],
        headlineMedium: [
          '28px',
          {
            fontWeight: '400',
            lineHeight: '36px',
            letterSpacing: '0',
          },
        ],
        headlineSmall: [
          '24px',
          {
            fontWeight: '400',
            lineHeight: '32px',
            letterSpacing: '0',
          },
        ],
        titleLarge: [
          '22px',
          {
            fontWeight: '400',
            lineHeight: '28px',
            letterSpacing: '0',
          },
        ],
        titleMedium: [
          '16px',
          {
            fontWeight: '500',
            lineHeight: '24px',
            letterSpacing: '0.15px',
          },
        ],
        titleSmall: [
          '14px',
          {
            fontWeight: '500',
            lineHeight: '20px',
            letterSpacing: '0.1px',
          },
        ],
        bodyLarge: [
          '16px',
          {
            fontWeight: '400',
            lineHeight: '24px',
            letterSpacing: '0.5px',
          },
        ],
        bodyMedium: [
          '14px',
          {
            fontWeight: '400',
            lineHeight: '20px',
            letterSpacing: '0.25px',
          },
        ],
        bodySmall: [
          '12px',
          {
            fontWeight: '400',
            lineHeight: '16px',
            letterSpacing: '0.4px',
          },
        ],
        labelLarge: [
          '14px',
          {
            fontWeight: '500',
            lineHeight: '20px',
            letterSpacing: '0.1px',
          },
        ],
        labelMedium: [
          '12px',
          {
            fontWeight: '500',
            lineHeight: '16px',
            letterSpacing: '0.5px',
          },
        ],
        labelSmall: [
          '11px',
          {
            fontWeight: '500',
            lineHeight: '16px',
            letterSpacing: '0.5px',
          },
        ],
      },
      transitionDuration: {
        short1: '50ms',
        short2: '100ms',
        short3: '150ms',
        short4: '200ms',
        medium1: '250ms',
        medium2: '300ms',
        medium3: '350ms',
        medium4: '400ms',
        long1: '450ms',
        long2: '500ms',
        long3: '550ms',
        long4: '600ms',
        extraLong1: '700ms',
        extraLong2: '800ms',
        extraLong3: '900ms',
        extraLong4: '1000ms',
      },
      transitionDelay: {
        short1: '50ms',
        short2: '100ms',
        short3: '150ms',
        short4: '200ms',
        medium1: '250ms',
        medium2: '300ms',
        medium3: '350ms',
        medium4: '400ms',
        long1: '450ms',
        long2: '500ms',
        long3: '550ms',
        long4: '600ms',
        extraLong1: '700ms',
        extraLong2: '800ms',
        extraLong3: '900ms',
        extraLong4: '1000ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.2, 0, 0, 1)',
        standardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
        standardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
        emphasized: 'cubic-bezier(0.2, 0, 0, 1.0)',
        emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
        emphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
        legacy: 'cubic-bezier(0.4, 0, 0.2, 1.0)',
        legacyDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',
        legacyAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
        linear: 'cubic-bezier(0, 0, 1, 1)',
      },
    },
  },
  plugins: [],
};